### PR TITLE
Add support for decimal pricing and transform_usage

### PR DESCRIPTION
**Pull request by magni-**
I haven't written Go in years (and never wrote much to begin with), but hopefully this looks good.

I only updated Stripe to the version that added support for decimal pricing, should I instead bump it up to the latest?

edit: ~indenting looks all over the place in the diff despite being fine in my editor, will fix~ fixed

`make test` doesn't pass yet, will update when it does.

### CODE REVIEW

**Review by franckverrot — COMMENTED** [review]
Salut Paul,

Thanks for working on this.  Hit me up whenever you want a merge, I’ll review.

**Comment by magni-** [comment]
Tests pass locally:
```
# clean Stripe test account, no `terraform.tfstate` file to start

$ make test
...
Apply complete! Resources: 10 added, 0 changed, 0 destroyed.
...
$ make test
...
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
...
```

Things look good in Stripe as well:
image

**Comment by magni-** [comment]
Salut @franckverrot!

It's late here, I didn't realize you had commented 🤦‍♂ This should be ready for review now.

**Comment by magni-** [comment]
We're now using this branch in production at RainforestQA, working great 👍

**Comment by franckverrot** [comment]
Awesome, thanks, do you mind giving the official release a try? https://github.com/franckverrot/terraform-provider-stripe/releases/tag/1.4.0

Thanks!

**Comment by franckverrot** [comment]
oh, merged offline also, I had to update one of your commit to vendor the dependencies and squashed the 3 other ones.

**Pull request closed without merging**
